camera0: rtsp://172.16.33.186:8554/cam
camera1: rtsp://172.16.33.188:8554/cam
frame_width: 1920
frame_height: 1080
mono_calibration_frames: 15
stereo_calibration_frames: 15
view_resize: 1
checkerboard_box_size_scale : 1.8
checkerboard_rows: 7
checkerboard_columns: 10
cooldown: 200
